#pragma once
constexpr size_t INCREMENTAL_MERKLE_TREE_DEPTH = 29;
constexpr size_t INCREMENTAL_MERKLE_TREE_DEPTH_TESTING = 4;

constexpr size_t SAPLING_INCREMENTAL_MERKLE_TREE_DEPTH = 32;

constexpr size_t NOTEENCRYPTION_AUTH_BYTES = 16;

constexpr size_t ZC_NOTEPLAINTEXT_LEADING = 1;
constexpr size_t ZC_V_SIZE = 8;
constexpr size_t ZC_RHO_SIZE = 32;
constexpr size_t ZC_R_SIZE = 32;
constexpr size_t ZC_MEMO_SIZE = 512;
constexpr size_t ZC_DIVERSIFIER_SIZE = 11;
constexpr size_t ZC_JUBJUB_POINT_SIZE = 32;
constexpr size_t ZC_JUBJUB_SCALAR_SIZE = 32;

constexpr size_t ZC_NOTEPLAINTEXT_SIZE = (ZC_NOTEPLAINTEXT_LEADING + ZC_V_SIZE + ZC_RHO_SIZE + ZC_R_SIZE + ZC_MEMO_SIZE);

constexpr size_t ZC_SAPLING_ENCPLAINTEXT_SIZE = (ZC_NOTEPLAINTEXT_LEADING + ZC_DIVERSIFIER_SIZE + ZC_V_SIZE + ZC_R_SIZE + ZC_MEMO_SIZE);
constexpr size_t ZC_SAPLING_OUTPLAINTEXT_SIZE = (ZC_JUBJUB_POINT_SIZE + ZC_JUBJUB_SCALAR_SIZE);

constexpr size_t ZC_SAPLING_ENCCIPHERTEXT_SIZE = (ZC_SAPLING_ENCPLAINTEXT_SIZE + NOTEENCRYPTION_AUTH_BYTES);
constexpr size_t ZC_SAPLING_OUTCIPHERTEXT_SIZE = (ZC_SAPLING_OUTPLAINTEXT_SIZE + NOTEENCRYPTION_AUTH_BYTES);
